tracklist_search_task:
  description: >
    Find the tracklist for the dj set {dj_set}
  expected_output: >
    A structured tracklist of the dj set. 
    You must use the following websites to find the tracklist, following 
    the order of the list:
    - 1001tracklists.com
    - trackid.net
    If a tracklist presents gaps, you must fill them with a placeholder track.
    The placeholder track must be "ID <ID number> - <dj_set>" by artist "ID",
    where <ID number> is current count of ID tracks in the tracklist.
    A gap is defined as a period of time between the beginning and the end of
    the tracklist that is not filled with a track.
    Sometimes the first track will have a blank instead of the 00:00 timestamp.
    In this case, you must fill it with the 00:00 timestamp.
    A track must always have a start and end timestamp.
    If two tracks have the same timestamp, there either is no information on 
    the transition or there is uncertainty about the right track. In this case,
    make an informed decision based on context and length of gap.
  agent: tracklist_finder
